services:
  app:
    build:
      context: .
      args:
        - RUBY_VERSION=$RUBY_VERSION
        - SOLARGRAPH_VERSION=$SOLARGRAPH_VERSION
    volumes:
      - bundle:/usr/local/bundle
      - $SOURCE_PATH:$SOURCE_PATH
    tty: true
    command: [
      "solargraph", "socket",
      "--host", "0.0.0.0",
      "--port", "7658"
    ]
    ports:
      - $PORT:7658
    restart: always

volumes:
  bundle:
